name: CI Github Pages
on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install  ️ 
        run: pnpm install
      - name: Build
        run: pnpm run build --filter @bp/example
    
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages 
          folder: packages/example/distname: CI Github Pages
on:
  push:
    branches:
      - master 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install  ️ 
        run: pnpm install
      - name: Build
        run: pnpm run build --filter @bp/example
    
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages 
          folder: packages/example/dist